### ISSUE TITLE
[1.12.2] Issue (In MultiMC Log)

### ISSUE THREAD

**Issue by Preminenc3** [GenDeathrow/MPUtils#36] opened 2018-01-27 13:44 UTC
[07:41:56] [main/ERROR] [FML]: The mcmod.info file in MPUtils-1.12-1.4.1.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 12 column 5 path $[0].credits
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:62) [MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:58) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:138) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:401) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 12 column 5 path $[0].credits
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[Streams.class:?]
	... 27 more

**Comment by GenDeathrow** [comment] 2018-01-28 08:31
no idea.. I will look into it.. but just glancing of my mcmod info file.. its a valid json.. so wonder if something happens during the build phase.

**Comment by ninjamask** [comment] 2018-02-12 17:09
```[
{
  "modid": "mputils",
  "name": "ModPack Utilities",
  "description": "will add various tools for modpack developers",
  "version": "1.4.1",
  "mcversion": "1.12",
  "url": "http://minecraft.curseforge.com/members/GenDeathrow/projects",
  "updateUrl": "",
  "authorList": ["GenDeathrow", "Darkosto"],
  "credits": "Darkosto for original idea to this mod! And all my Patreon supporters! Like Tedyhere,
  "logoFile": "MPUTILS_small.png",
  "screenshots": [],
  "dependencies": []
}
]
```

That is extracted from `MPUtils-1.12-1.4.1.jar` which is part of the "Lost Souls - Forever Stranded" modpack. https://www.curseforge.com/minecraft/modpacks/forever-stranded-lost-souls

The credit line is missing a closing "

**Comment by GenDeathrow** [comment] 2018-02-12 20:29
Ok I see where the issue is. But in my dev version it was already fixed. I cant tell you what version it got fixed on cause I cant remember, but you are on v1.4.1 and I just put out v1.5.5. I do appreciate you reporting it thanks.

**Closed as completed by GenDeathrow** 2018-02-12 20:29 UTC
